apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-lab
spec:
  template:
    spec:
      containers:
        - name: delivery-lab
          args:
            - --delivery-lab.demo.failure-mode=readiness
