apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: docker.io/thecodealchemist/delivery-lab
    digest: sha256:a7d5be9c070ab4c951f49c0d105dc1fb13d52c2d4e0b1e043b70342297b533f1

# commented out to restore the working state
#patches:
#  - path: checkpoint-2-startup-failure.yaml