apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
images:
  - name: docker.io/thecodealchemist/delivery-lab
    digest: sha256:55604647b85071d9b6c59166b7692cf7152224e8306c2c4710f8dbc43cd8c563
