apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: delivery-lab-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thecodealchemist/delivery-lab
    targetRevision: main
    path: deploy/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
